---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: NetApp은 제품과 서비스를 지속적으로 개선 및 개선하고 있습니다. 다음은 최신 버전의 Astra Trident에 포함된 최신 기능, 개선 사항 및 버그 수정 사항입니다. 
---
= 릴리즈 노트
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


릴리즈 노트 최신 버전의 Astra Trident에 새로운 기능, 개선 사항 및 버그 수정 사항에 대한 정보를 제공합니다.


WARNING: 를 클릭합니다 `tridentctl` 설치 프로그램 zip 파일에 제공된 Linux용 바이너리는 테스트되고 지원되는 버전입니다. 에 유의하십시오 `macos` 에 제공된 바이너리 `/extras` zip 파일의 일부가 테스트되지 않았거나 지원되지 않습니다.



== 새로운 기능

NetApp은 제품과 서비스를 지속적으로 개선 및 개선하고 있습니다. Astra Trident에서 사용할 수 있는 최신 기능과 특징을 소개합니다.



=== Astra Trident 21.07.02

* XFS 볼륨의 클론을 소스 볼륨과 동일한 노드에 마운트할 수 없는 문제가 해결되었습니다.




==== 향상된 기능

* Kubernetes 1.22에 대한 지원이 추가되었습니다.
* Trident 운영자 및 제어 차트를 Kubernetes 1.22와 함께 사용할 수 있도록 했습니다.


을 참조하십시오 https://github.com/NetApp/trident/releases["Astra Trident GitHub를 참조하십시오"^] 를 참조하십시오.



=== Astra Trident 21.07.01

* 다른 이미지의 사용자 지정 YAML 설치 프로그램 문제 해결.
* 스냅샷 크기 계산 문제가 해결되었습니다.


을 참조하십시오 https://github.com/NetApp/trident/releases/tag/v21.07.1["Astra Trident GitHub를 참조하십시오"^] 를 참조하십시오.



=== Astra Trident 21.07

Astra Trident 21.07.0 은 * 다운로드할 수 없습니다 *. 에 적용된 변경 사항 `snapshotReserve` 버전 21.07.0을 사용하면 CSI가 발생할 수 있습니다 `VolumeSnapshots` PersistentVolumeClaim 생성에 사용할 수 없습니다.

21.07.0 버전으로 이미 업그레이드한 경우에는 새로 만든 을 삭제하는 것이 좋습니다 `VolumeSnapshots` (버전 21.07.0으로 제공) 이전 릴리즈로 다운그레이드합니다.

을 참조하십시오 https://github.com/NetApp/trident/releases/tag/v21.07.0["Astra Trident GitHub를 참조하십시오"^] 를 참조하십시오.



== 알려진 문제

알려진 문제점은 제품을 성공적으로 사용하지 못하게 만들 수 있는 문제를 식별합니다.

* Astra Trident가 이제 공란을 적용합니다 `fsType` (`fsType=""`)이 없는 볼륨의 경우 `fsType` StorageClass에 지정됩니다. Kubernetes 1.17 이상으로 작업할 경우 Trident는 공백을 제공할 수 있도록 지원합니다 `fsType` NFS 볼륨용. iSCSI 볼륨의 경우 를 설정해야 합니다 `fsType` 를 적용할 때 StorageClass에 대해 `fsGroup` 보안 컨텍스트 사용.
* 여러 Astra Trident 인스턴스에서 백엔드를 사용할 경우 각 백엔드 구성 파일은 서로 달라야 합니다 `storagePrefix` ONTAP 백엔드에 대한 값이거나 다른 값을 사용합니다 `TenantName` SolidFire 백엔드의 경우. Astra Trident는 Astra Trident의 다른 인스턴스가 생성한 볼륨을 감지할 수 없습니다. Astra Trident가 볼륨 생성을 idemptent 작업으로 처리하므로 ONTAP 또는 SolidFire 백엔드에서 기존 볼륨을 생성하려고 하면 성공합니다. If(경우 `storagePrefix` 또는 `TenantName` 서로 다를 수 없습니다. 동일한 백엔드에서 생성된 볼륨의 이름 충돌이 있을 수 있습니다.
* Astra Trident 설치 시(사용 `tridentctl` 또는 Trident Operator)를 사용하여 사용할 수 있습니다 `tridentctl` Astra Trident를 관리하려면 을(를) 확인해야 합니다 `KUBECONFIG` 환경 변수가 설정되었습니다. 이는 Kubernetes 클러스터를 나타내는 데 필요합니다 `tridentctl` 에 대해 작업해야 합니다. 여러 Kubernetes 환경을 사용할 때는 가 반드시 에 적합해야 합니다 `KUBECONFIG` 파일을 정확하게 소싱합니다.
* iSCSI PVS에 대해 온라인 공간 재확보를 수행하려면 작업자 노드의 기본 OS에 볼륨에 마운트 옵션을 전달해야 할 수 있습니다. 이 내용은 가 필요한 RHEL/RedHat CoreOS 인스턴스에 적용됩니다 `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["마운트 옵션"^]에 mountmounted 폐기 옵션이 포함되어 있는지 확인합니다[`StorageClass`^ ] 를 클릭하여 온라인 블록 버기를 지원합니다.
* Kubernetes 클러스터당 Astra Trident 인스턴스가 두 개 이상 있는 경우, Astra Trident가 다른 인스턴스와 통신할 수 없고 자신이 생성한 다른 볼륨을 검색할 수 없기 때문에 클러스터 내에서 둘 이상의 인스턴스가 실행될 경우 예기치 않거나 잘못된 동작이 발생합니다. Kubernetes 클러스터당 하나의 Astra Trident 인스턴스만 있어야 합니다.
* Astra Trident 기반인 경우 `StorageClass` Astra Trident가 오프라인인 동안 Kubernetes에서 객체가 삭제되며, Astra Trident는 온라인 상태로 돌아올 때 데이터베이스에서 해당 스토리지 클래스를 제거하지 않습니다. 를 사용하여 이러한 스토리지 클래스를 삭제해야 합니다 `tridentctl` 또는 REST API를 선택합니다.
* 사용자가 해당 PVC를 삭제하기 전에 Astra Trident가 프로비저닝한 PV를 삭제하는 경우 Astra Trident는 백업 볼륨을 자동으로 삭제하지 않습니다. 를 통해 볼륨을 제거해야 합니다 `tridentctl` 또는 REST API를 선택합니다.
* FlexGroup은 애그리게이트 세트가 각 프로비저닝 요청에서 고유하지 않으면 한 번에 둘 이상의 ONTAP를 동시에 프로비저닝할 수 없습니다.
* IPv6를 통해 Astra Trident를 사용할 때는 을 지정해야 합니다 `managementLIF` 및 `dataLIF` 백엔드 정의에서 대괄호로 묶습니다. 예를 들면, 다음과 같습니다. ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``.
* 를 사용하는 경우 `solidfire-san` OpenShift 4.5를 사용하는 드라이버 기본 작업자 노드가 CHAP 인증 알고리즘으로 MD5를 사용하는지 확인합니다.




== 자세한 내용을 확인하십시오

* https://github.com/NetApp/trident["Astra Trident GitHub를 참조하십시오"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Astra Trident 블로그"^]

